import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbars";
import { Climate_Crisis, Josefin_Sans } from 'next/font/google'

const CC = Climate_Crisis({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-cc'
});

const JS = Josefin_Sans({
  weight: ['300','500'],
  subsets: ['latin'],
  variable: '--font-js'
});

export const metadata: Metadata = {
  title: "TechCenter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${CC.variable} ${JS.variable}`}>
      <body  className="antialiased bg-gray-100 font-[family-name:var(--font-js)] pt-16">
        <Navbar />
        {children}
      </body>
    </html>
  );
}